#!/bin/bash

# Quick setup script for Traefik secrets on teaching VM
# Run this on the teaching VM if automated deployment fails

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEACHING_DIR="$(dirname "$SCRIPT_DIR")"
TRAEFIK_DIR="$TEACHING_DIR/traefik"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Traefik Secrets Setup (Teaching VM)${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if we're in the right directory
if [ ! -f "$TRAEFIK_DIR/docker-compose.yaml" ]; then
    echo -e "${RED}Error: docker-compose.yaml not found in $TRAEFIK_DIR${NC}"
    echo "Please run this script from teaching/scripts directory"
    exit 1
fi

cd "$TRAEFIK_DIR"

echo -e "${YELLOW}This script will set up Traefik secrets for the teaching VM.${NC}"
echo ""

# Ask for Cloudflare settings
echo -e "${BLUE}Step 1: Cloudflare Configuration${NC}"
read -p "Enter Cloudflare email [anand.krs@gmail.com]: " CF_EMAIL
CF_EMAIL=${CF_EMAIL:-anand.krs@gmail.com}

read -p "Enter your Cloudflare API Token: " CF_TOKEN

if [ -z "$CF_TOKEN" ]; then
    echo -e "${RED}Error: API token cannot be empty${NC}"
    exit 1
fi

echo ""

# Ask for Traefik dashboard credentials
echo -e "${BLUE}Step 2: Traefik Dashboard Credentials${NC}"
read -p "Enter dashboard username [admin]: " DASH_USER
DASH_USER=${DASH_USER:-admin}

read -s -p "Enter dashboard password: " DASH_PASS
echo ""

if [ -z "$DASH_PASS" ]; then
    echo -e "${RED}Error: Password cannot be empty${NC}"
    exit 1
fi

echo ""

# Create .env file (Teaching VM uses simple env vars, not htpasswd hash)
echo -e "${BLUE}Step 3: Creating .env file${NC}"
cat > .env << EOF
# Traefik Environment Configuration
# Generated by setup-traefik-secrets.sh on $(date)

# Cloudflare Configuration
CLOUDFLARE_EMAIL=$CF_EMAIL
CLOUDFLARE_API_TOKEN=$CF_TOKEN

# Domain
DOMAIN=lab.nexuswarrior.site

# Traefik Dashboard Authentication
TRAEFIK_DASHBOARD_USER=$DASH_USER
TRAEFIK_DASHBOARD_PASSWORD=$DASH_PASS
EOF

chmod 600 .env
echo -e "${GREEN}✓ .env file created${NC}"

echo ""

# Ensure acme.json exists with correct permissions
echo -e "${BLUE}Step 4: Setting up acme.json${NC}"
if [ ! -f "config/acme.json" ]; then
    touch config/acme.json
    echo -e "${GREEN}✓ acme.json created${NC}"
else
    echo -e "${YELLOW}acme.json already exists${NC}"
fi

chmod 600 config/acme.json
echo -e "${GREEN}✓ acme.json permissions set to 600${NC}"

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Summary:"
echo "  - .env: Created with Cloudflare credentials"
echo "  - acme.json: Ready for Let's Encrypt"
echo "  - Domain: lab.nexuswarrior.site"
echo ""
echo "Next steps:"
echo "  1. Review the generated .env file"
echo "  2. Deploy Traefik: docker compose up -d"
echo "  3. Check logs: docker compose logs -f"
echo "  4. Access dashboard: https://traefik.lab.nexuswarrior.site"
echo ""
