http:
  routers:
    anand-code-server:
      rule: "Host(`anand.lab.nexuswarrior.site`)"
      entryPoints:
        - websecure
      service: anand-code-server
  services:
    anand-code-server:
      loadBalancer:
        servers:
          - url: "http://192.168.10.29:8449"