---
services:
  twingate-connector:
    image: twingate/connector:latest
    container_name: twingate-connector
    restart: unless-stopped
    environment:
      - TWINGATE_NETWORK=${TWINGATE_NETWORK}
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      - TWINGATE_LOG_LEVEL=4
      - TWINGATE_LOG_ANALYTICS=v1
    networks:
      - proxy
    sysctls:
      - net.ipv4.ping_group_range=0 2147483647
      - net.ipv4.ip_unprivileged_port_start=0

networks:
  proxy:
    external: true
